# Data Cleaning
In this notebook, we will perform data cleaning:
- Load the dataset
- Check for missing values
- Convert categorical variables to appropriate formats
- Handle errors or inconsistencies in the data

In [34]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [28]:
%load_ext autoreload
%autoreload 2
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

from utils.data_cleaning import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [20]:
df = pd.read_csv('../data/raw/bike_sharing.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   season      17379 non-null  str
 1   year        17379 non-null  int64
 2   month       17379 non-null  int64
 3   hour        17379 non-null  int64
 4   holiday     17379 non-null  bool
 5   weekday     17379 non-null  int64
 6   workingday  17379 non-null  bool
 7   weather     17379 non-null  str
 8   temp        17379 non-null  float64
 9   feel_temp   17379 non-null  float64
 10  humidity    17379 non-null  float64
 11  windspeed   17379 non-null  float64
 12  count       17379 non-null  int64
dtypes: bool(2), float64(4), int64(5), str(2)
memory usage: 1.5 MB

In [5]:
df.head()

,season,year,month,hour,holiday,weekday,workingday,weather,temp,feel_temp,humidity,windspeed,count
0,spring,0,1,0,False,6,False,clear,9.84,14.395,0.81,0.0,16
1,spring,0,1,1,False,6,False,clear,9.02,13.635,0.80,0.0,40
2,spring,0,1,2,False,6,False,clear,9.02,13.635,0.80,0.0,32
3,spring,0,1,3,False,6,False,clear,9.84,14.395,0.75,0.0,13
4,spring,0,1,4,False,6,False,clear,9.84,14.395,0.75,0.0,1

There are no missing values, but the `season` and `weather` column is of type `str`, which means it may contains categorical data.
After checking unique values. We can convert it to a more suitable format for analysis.

In [22]:
df.season = df.season.astype('category')
df.season.unique()

['spring', 'summer', 'fall', 'winter']
Categories (4, str): ['fall', 'spring', 'summer', 'winter']

In [23]:
df.weather = df.weather.astype('category')
df.weather.unique()

['clear', 'misty', 'rain', 'heavy_rain']
Categories (4, str): ['clear', 'heavy_rain', 'misty', 'rain']

In [37]:
df_one_hot = pd.get_dummies(df, columns=["season", "weather"], drop_first=True)

In [38]:
df_one_hot.head()

,year,month,hour,holiday,weekday,workingday,temp,feel_temp,humidity,windspeed,count,season_spring,season_summer,season_winter,weather_heavy_rain,weather_misty,weather_rain
0,0,1,0,False,6,False,9.84,14.395,0.81,0.0,16,True,False,False,False,False,False
1,0,1,1,False,6,False,9.02,13.635,0.80,0.0,40,True,False,False,False,False,False
2,0,1,2,False,6,False,9.02,13.635,0.80,0.0,32,True,False,False,False,False,False
3,0,1,3,False,6,False,9.84,14.395,0.75,0.0,13,True,False,False,False,False,False
4,0,1,4,False,6,False,9.84,14.395,0.75,0.0,1,True,False,False,False,False,False

In [33]:
show_unique(df, ["year", "month", "weekday", "hour"])

Column: year
Unique count: 2
Column: month
Unique count: 12
Column: weekday
Unique count: 7
Column: hour
Unique count: 24

As the data needs to be checked before selecting a technique for splitting the time columns, this will be done during the EDA.